# Generated by Django 4.0.3 on 2022-03-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=75)),
                ('titulo', models.CharField(max_length=100)),
                ('menssagem', models.TextField(max_length=256)),
            ],
        ),
    ]
